syntax = "proto3";

package rag;

option java_multiple_files = true;
option java_package = "io.hppn.unirag.grpc"; 
option java_outer_classname = "RagServiceProto";

// SERVICE DEFINITION
service RagEngineService {
  // 1. Nạp Doc (Client Streaming)
  rpc UploadDocument(stream UploadRequest) returns (UploadResponse);

  // 2. Xóa Doc (Unary - Gọi 1 lần)
  rpc DeleteDocument(DeleteRequest) returns (DeleteResponse);

  // 3. Truy vấn RAG (Server Streaming)
  rpc QueryRag(QueryRequest) returns (stream QueryResponse);
}

// MESSAGES

// --- Upload ---
message UploadRequest {
  string doc_id = 1; 
  bytes chunk_data = 2; 
}

message UploadResponse {
  bool success = 1;
  string message = 2;
}

// --- Delete ---
message DeleteRequest {
  string doc_id = 1;
}

message DeleteResponse {
  bool success = 1;
  string message = 2;
}

// --- Query ---
message QueryRequest {
  string question = 1;
  repeated string doc_ids = 2; // Danh sách DocID. Rỗng = tìm toàn bộ
}

message QueryResponse {
  string answer_chunk = 1; // Từng đoạn text trả về
}