# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rag_service_pb2 as rag__service__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in rag_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiEngineServiceStub(object):
    """Định nghĩa Service chính
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestDocument = channel.unary_unary(
                '/unirag.grpc.AiEngineService/IngestDocument',
                request_serializer=rag__service__pb2.IngestRequest.SerializeToString,
                response_deserializer=rag__service__pb2.IngestResponse.FromString,
                _registered_method=True)
        self.AskQuestion = channel.unary_unary(
                '/unirag.grpc.AiEngineService/AskQuestion',
                request_serializer=rag__service__pb2.QueryRequest.SerializeToString,
                response_deserializer=rag__service__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.AskQuestionStream = channel.unary_stream(
                '/unirag.grpc.AiEngineService/AskQuestionStream',
                request_serializer=rag__service__pb2.QueryRequest.SerializeToString,
                response_deserializer=rag__service__pb2.QueryStreamResponse.FromString,
                _registered_method=True)


class AiEngineServiceServicer(object):
    """Định nghĩa Service chính
    """

    def IngestDocument(self, request, context):
        """1. Gửi file lên để xử lý (Ingestion)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AskQuestion(self, request, context):
        """2. Trả lời câu hỏi (Query)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AskQuestionStream(self, request, context):
        """3. Trả lời câu hỏi dạng Stream (Dành cho UI gõ từng chữ)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiEngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestDocument,
                    request_deserializer=rag__service__pb2.IngestRequest.FromString,
                    response_serializer=rag__service__pb2.IngestResponse.SerializeToString,
            ),
            'AskQuestion': grpc.unary_unary_rpc_method_handler(
                    servicer.AskQuestion,
                    request_deserializer=rag__service__pb2.QueryRequest.FromString,
                    response_serializer=rag__service__pb2.QueryResponse.SerializeToString,
            ),
            'AskQuestionStream': grpc.unary_stream_rpc_method_handler(
                    servicer.AskQuestionStream,
                    request_deserializer=rag__service__pb2.QueryRequest.FromString,
                    response_serializer=rag__service__pb2.QueryStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'unirag.grpc.AiEngineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('unirag.grpc.AiEngineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiEngineService(object):
    """Định nghĩa Service chính
    """

    @staticmethod
    def IngestDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unirag.grpc.AiEngineService/IngestDocument',
            rag__service__pb2.IngestRequest.SerializeToString,
            rag__service__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AskQuestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unirag.grpc.AiEngineService/AskQuestion',
            rag__service__pb2.QueryRequest.SerializeToString,
            rag__service__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AskQuestionStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/unirag.grpc.AiEngineService/AskQuestionStream',
            rag__service__pb2.QueryRequest.SerializeToString,
            rag__service__pb2.QueryStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
