# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rag_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'rag_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11rag_service.proto\x12\x0bunirag.grpc\"\x7f\n\x10\x44ocumentMetadata\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x11\n\tfile_name\x18\x03 \x01(\t\x12\x16\n\tfolder_id\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x0c\n\x04tags\x18\x05 \x03(\tB\x0c\n\n_folder_id\"\x7f\n\x0e\x44ocumentFilter\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x18\n\x0b\x64ocument_id\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x16\n\tfolder_id\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x0c\n\x04tags\x18\x04 \x03(\tB\x0e\n\x0c_document_idB\x0c\n\n_folder_id\"n\n\rIngestRequest\x12\x14\n\x0c\x66ile_content\x18\x01 \x01(\x0c\x12\x16\n\x0e\x66ile_extension\x18\x02 \x01(\t\x12/\n\x08metadata\x18\x03 \x01(\x0b\x32\x1d.unirag.grpc.DocumentMetadata\"2\n\x0eIngestResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"Y\n\x0cQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\x12+\n\x06\x66ilter\x18\x03 \x01(\x0b\x32\x1b.unirag.grpc.DocumentFilter\"\x1f\n\rQueryResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\"$\n\x13QueryStreamResponse\x12\r\n\x05\x63hunk\x18\x01 \x01(\t2\xf6\x01\n\x0f\x41iEngineService\x12I\n\x0eIngestDocument\x12\x1a.unirag.grpc.IngestRequest\x1a\x1b.unirag.grpc.IngestResponse\x12\x44\n\x0b\x41skQuestion\x12\x19.unirag.grpc.QueryRequest\x1a\x1a.unirag.grpc.QueryResponse\x12R\n\x11\x41skQuestionStream\x12\x19.unirag.grpc.QueryRequest\x1a .unirag.grpc.QueryStreamResponse0\x01\x42(\n\x13io.hppn.unirag.grpcB\x0fRagServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023io.hppn.unirag.grpcB\017RagServiceProtoP\001'
  _globals['_DOCUMENTMETADATA']._serialized_start=34
  _globals['_DOCUMENTMETADATA']._serialized_end=161
  _globals['_DOCUMENTFILTER']._serialized_start=163
  _globals['_DOCUMENTFILTER']._serialized_end=290
  _globals['_INGESTREQUEST']._serialized_start=292
  _globals['_INGESTREQUEST']._serialized_end=402
  _globals['_INGESTRESPONSE']._serialized_start=404
  _globals['_INGESTRESPONSE']._serialized_end=454
  _globals['_QUERYREQUEST']._serialized_start=456
  _globals['_QUERYREQUEST']._serialized_end=545
  _globals['_QUERYRESPONSE']._serialized_start=547
  _globals['_QUERYRESPONSE']._serialized_end=578
  _globals['_QUERYSTREAMRESPONSE']._serialized_start=580
  _globals['_QUERYSTREAMRESPONSE']._serialized_end=616
  _globals['_AIENGINESERVICE']._serialized_start=619
  _globals['_AIENGINESERVICE']._serialized_end=865
# @@protoc_insertion_point(module_scope)
