# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rag_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'rag_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11rag_service.proto\x12\x03rag\"3\n\rUploadRequest\x12\x0e\n\x06\x64oc_id\x18\x01 \x01(\t\x12\x12\n\nchunk_data\x18\x02 \x01(\x0c\"2\n\x0eUploadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1f\n\rDeleteRequest\x12\x0e\n\x06\x64oc_id\x18\x01 \x01(\t\"2\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"1\n\x0cQueryRequest\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x0f\n\x07\x64oc_ids\x18\x02 \x03(\t\"%\n\rQueryResponse\x12\x14\n\x0c\x61nswer_chunk\x18\x01 \x01(\t2\xbf\x01\n\x10RagEngineService\x12;\n\x0eUploadDocument\x12\x12.rag.UploadRequest\x1a\x13.rag.UploadResponse(\x01\x12\x39\n\x0e\x44\x65leteDocument\x12\x12.rag.DeleteRequest\x1a\x13.rag.DeleteResponse\x12\x33\n\x08QueryRag\x12\x11.rag.QueryRequest\x1a\x12.rag.QueryResponse0\x01\x42(\n\x13io.hppn.unirag.grpcB\x0fRagServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023io.hppn.unirag.grpcB\017RagServiceProtoP\001'
  _globals['_UPLOADREQUEST']._serialized_start=26
  _globals['_UPLOADREQUEST']._serialized_end=77
  _globals['_UPLOADRESPONSE']._serialized_start=79
  _globals['_UPLOADRESPONSE']._serialized_end=129
  _globals['_DELETEREQUEST']._serialized_start=131
  _globals['_DELETEREQUEST']._serialized_end=162
  _globals['_DELETERESPONSE']._serialized_start=164
  _globals['_DELETERESPONSE']._serialized_end=214
  _globals['_QUERYREQUEST']._serialized_start=216
  _globals['_QUERYREQUEST']._serialized_end=265
  _globals['_QUERYRESPONSE']._serialized_start=267
  _globals['_QUERYRESPONSE']._serialized_end=304
  _globals['_RAGENGINESERVICE']._serialized_start=307
  _globals['_RAGENGINESERVICE']._serialized_end=498
# @@protoc_insertion_point(module_scope)
